#Vault

spring.application.name=docker

spring.config.import=vault://

spring.cloud.vault.uri=http://10.4.72.9:8200

spring.cloud.vault.token=${VAULT_TOKEN}

spring.cloud.vault.ssl.enabled=false

spring.cloud.vault.kv.backend=secret

spring.cloud.vault.kv.backend-version=2

spring.cloud.vault.kv.default-context=docker

#Database

spring.datasource.url=${db.url}

spring.datasource.username=${db.username}

spring.datasource.password=${db.password}

spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.show-sql = true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.use-new-id-generator-mappings= false

spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto=none

management.health.db.enabled=true

spring.datasource.hikari.maximum-pool-size=15

spring.datasource.hikari.minimum-idle=5

spring.datasource.hikari.connection-timeout=8000

spring.datasource.hikari.idle-timeout=300000

spring.datasource.hikari.max-lifetime=1800000

spring.datasource.hikari.keepalive-time=30000

spring.datasource.hikari.leak-detection-threshold=20000

spring.datasource.hikari.initialization-fail-timeout=0

spring.datasource.hikari.auto-commit=true

spring.datasource.hikari.pool-name=HikariPool

#Spring cloud

spring.cloud.compatibility-verifier.enabled=false


#External URL's

native.wallet.url=https://offredhat.digitaltrusttech.com/VG/IssueEcCertificate

native.cert.url=https://offredhat.digitaltrusttech.com/VG/IssueCertificate

ra.service.pki = http://10.4.72.9:7080/PKIServiceTransactionHandler/transaction-handler/post/service/process-transaction

ra.service.authrizeduser = http://10.4.72.9:8085/SignatureWebService/api/digital/signature/post/user/status

verify.url = http://10.4.72.9:8085/SignatureWebService/api/digital/signature/post/verify

url.debit = http://10.4.72.9:7080/pricemodel

email.url= http://10.4.72.9:5006/sendemail

send.email.url=http://10.4.72.9:5006/sendbody

send.email.adminURL=http://10.4.72.9:5006/sendbody

orgLink.notifyurl=http://10.4.72.9:7014/send/notification

eoi.portal.link=https://staging.digitaltrusttech.com/login

verify.egp.vendorId=https://pde.staging.egpuganda.go.ug/

url.admin.emaillist=https://offredhat.digitaltrusttech.com/admin-portal/api/Users/GetAdminUsersList

save.client = https://offredhat.digitaltrusttech.com/idp/api/clients/SaveClient

application.uri =http://10.4.72.9:1002/

logout.uri = http://10.4.72.9:1002/logout/

redirect.uri = http://10.4.72.9:1002/


send.log = http://10.4.72.9:7013/kyc/api/organization/save

#EGP

egp.authorization.username=nita-u

egp.authorization.password=1}1E<$kEMcZ3VQ*f


#sentry

sentry.dsn=https://0a799ae8507b42fa86093a8aa288a53e@monitor.digitaltrusttech.com/15

sentry.environment=staging

sentry.traces-sample-rate=1.0

sentry.exception-resolver-order=-2147483647

sentry.debug=false

sentry.logging.minimum-event-level=info

sentry.logging.minimum-breadcrumb-level=debug

#Kafka

spring.kafka.bootstrap-servers=10.4.72.9:9092

com.dt.kafka.topic.central=central-log-topic

com.dt.kafka.topic.ra=ra-logs-topic

file.crt=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lKQUtaNnZlbkVyaVc2TUEwR0NTcUdTSWIzRFFFQkN3VUFNQ0F4SGpBY0JnTlYKQkFNTUZWVkhVR0Z6Y3lCVGFXZHVhVzVuSUZCdmNuUmhiREFlRncweU1qQTVNVFV3T1RRMU5ESmFGdzB5TXpBNQpNVFV3T1RRMU5ESmFNQ0F4SGpBY0JnTlZCQU1NRlZWSFVHRnpjeUJUYVdkdWFXNW5JRkJ2Y25SaGJEQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPZGUvNW1iRk4vdTdSdXlSR2RwbjIxeXVtOTkKYmlSUlhQNFVRUkVoQ2xYRHVZOFRMNjM2VHVwUjJGOXJWK295Nk5hWkdsVm1DQ21aQUZrVmhldDdRUk4xaUJvawpFUTlvQTFack5tdHcwTmxTUlY4U1dadnpMZ0txWGwwWkxMSUpidXpUQnpQeVl4RDVPSTZYRHkzZVI0aXhzaU9xCkZobmwzNWtUb0h6aFhRZFpEb0hteW8zUkEvQWJFZllnSDNYa3pzcGhVVDZaeUNBdDIzT21Ic3lQNDVuWm8wU1IKalNIREpzUWFLM1JQOUFVSVI0eVRWVjlSUUdFcTVESzUxSHBMeEcyZVpKR1c3OCs0SENTNXRUR2MyMmxPSktqMQowVWdNS25iczl0eHZHaTdkcDg0aWVxOTYrdHErdFk0allaWFQyY1JhWlpCam9kN3BUVGVRK3pjVzBoTUNBd0VBCkFhTlhNRlV3RGdZRFZSMFBBUUgvQkFRREFnR3VNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWQKRXdRRk1BTUJBZjh3SUFZRFZSMFJCQmt3RjRJVlZVZFFZWE56SUZOcFoyNXBibWNnVUc5eWRHRnNNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFCMkZVT0dpOGFGYlNtY3RQeTJmMHZtSngvSkw2dkJVVVlBa01zNXFCc3h4TjFUClhNYTdDanRMUmVHYnRMNy9idTFzN1lndWNERVZCR0J6OUttVmNxQll5bWk3cldlTzVJK1pGOHJDOG5nL3ZjZVgKdzB2ckJ2STRPTnFKbDYyck1HZGhJYTBrLytHbTl6NE1vL001ZVA3NEdjUjF4UUE4R0lLNnluMXNrYWZaMlJPRQpBSVhNTkx3QkNOaUxWbVBPbklzaWdtOGtRZGJnODR3YktEakV6QmlHN0pvQVIyZDZrV2pkTUNJcVF3UVFrTmI2CjdsK0FrcGpyZ2YxZ1pmcEQvT0Zud2dnblR0S21weHM1eVh4cVVaZ2wydFhONm9xL2hURVhtOEFuVFRGYmZnaWgKQkVnWkdPckV4elRGT0s3MGRUSzFwT0dlYlR6UnFUc3JtdEJKSDRiaAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

privatekey.for.license=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDnXv+ZmxTf7u0bskRnaZ9tcrpvfW4kUVz+FEERIQpVw7mPEy+t+k7qUdhfa1fqMujWmRpVZggpmQBZFYXre0ETdYgaJBEPaANWazZrcNDZUkVfElmb8y4Cql5dGSyyCW7s0wcz8mMQ+TiOlw8t3keIsbIjqhYZ5d+ZE6B84V0HWQ6B5sqN0QPwGxH2IB915M7KYVE+mcggLdtzph7Mj+OZ2aNEkY0hwybEGit0T/QFCEeMk1VfUUBhKuQyudR6S8RtnmSRlu/PuBwkubUxnNtpTiSo9dFIDCp27Pbcbxou3afOInqvevravrWOI2GV09nEWmWQY6He6U03kPs3FtITAgMBAAECggEAGlN7391+fZBxGEKrd9zT0B9KyV7LRoSfgSWK1ckdpO6VUYtMVI5zpkPTy9+p7DMIvUpEbc0jRqBrIrfJOicXG4C3EMpjyo36Oz4NviHjEadDz3KGEbGU3abG/+7aYBOktHu6iRWeYhMJdWgIyR5Oo2Ycr+QtiZrXW1KZYzw9WpV3FdsfMAe3kLbMkr0frHZ0RKU1P14EQFOPRFjSZ/Jhggnxs7rWF7jgbeQIjIOHUiNdlqubfNM93NSj5lqA6TTnMixqtvDti9v1DZ6rrskD2sqtCfvTlmPkqwtmiOfkubPoD6QDWJfZaSxlbulRLl4joGk6CORKjhGQRxXlWOBMGQKBgQD/4m3Ps3j+vSXYv2GG4KwbVGRa2xJFJn+4UFoGfJdz7s5GLCFXThSyUzTY+y3fQtcK+s0x457KXow2LuKQy+pqoKhz/a37QeWVrAqZhBqmjbcMIU2mJ5eLcimcBRDPPcA34+BwV6giLdy8b6cM+/smLK78th+kdI8WRXxwA4g7VwKBgQDnebyTEU9HroiyLMPM0DJBlZcBbGCg7wtbi6hq0NGgpJMl+PBnuUhaDJEyu7shcBXZu06G43PAIGayTnX2sEZafA7Mcz1s0eG8jlJNpZa2xQ0pvbJ7c7CPQ2EDbRoOmnGoO2lzrndbO22bfXxck42WW82EuYDgU1ATSeQOAdMlpQKBgCXUevmfBf9bRXIi8S84nhk4Q9Hu22efxnggYP7egqGgJ5zWP2Oh5otqo8CEegas4g/8fkOm7D3s9nu4OMTBcPmsoNrtIUCpQGD9W1/Q2QPQpcREVC+BYPU7vo0TbqXE8lsQ9IiHXRMYhq7RLvhLdJjzODeiUVFF7jWTtk71JrnnAoGAZEQTLxE8aixsAeHqHnnAizAk7PTpFkz1en4QQdSaOR+Qrc4bNJLJiFgRPQycjmtiy6Ga7krwBLUERxA9gNHyZ5d9QYpZfR2cznRHqmKj2h+ZCA+nlFoUjLn+9+D2fITh3qF9mCJmiRpA7C17BQ7VMeAqMee4r3LnKLPFGVwo/hECgYATgf2nhjO5U19hdJ/PZEJCZTBTbfjpz3NjfZsWZ/DG+IOfGV3CY0D5gsN2Ws2hJCsxAg4X5SGP6rMToDy0wbeU/GzayJzlvKnbiqKnLLIO+GxVEkehNz4H7NpBywWpep3o71uT4QgWXzqhGFTz/31sQQiCvf/3lzOCqpV0sWhdVw==


#Configurations

icp.env=true

return.multiple.sponsors=true

sample.spoc.name = sai

sample.spoc.mobile = 9598598595

validation.transaction.reference.enabled=false

face.threshold = 0.3

apply.forgenerate.licenses=true

send.only.adminemail=5

# max.adminEmails = 0 send all users

max.adminEmails = 5

nira.api.timetolive = 180

sponsor.linked.msg=New Sponsor Linked Successfully

egp.org.id=8b3bdf99-d26c-403e-ba93-dfa7377d04cb

privileges=credential_issuer,credential_verifier

#Email

spring.mail.host=${SMTP_SERVER}

spring.mail.port=${SMTP_PORT}

spring.mail.username=${SMTP_LOGIN}

spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

#Servelet

spring.transaction.default-timeout=30

server.connection-timeout=240000

spring.banner.location=classpath:/banner.txt

# ReDoc

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=false

springdoc.api-docs.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

