package com.dtt.organization.enums;

public enum PrivilegeServiceName {

    DIGITAL_SIGNATURE,
    ESEAL_SIGNATURE,
    USER_SUBSCRIPTION,
    ONBOARDING,
    SUBSCRIBER_CERTIFICATES,
    ESEAL_CERTIFICATE,
    SIGNATURE_VERIFICATION,
    IS_LSA,
    IS_ESEAL_SIGNATORY,
    IS_ESEAL_PREPARATORY,
    IS_ORG_SIGNATORY,
    IS_TEMPALTE,
    IS_BULK_SIGN,
    IS_DELEGATE
}
